xrdb -merge ~/.Xresources
xset s off
feh --randomize --bg-fill ${HOME}/.wallpapers/*
xkbcomp ${XDG_CONFIG_HOME}/x11/xkb_keymap $DISPLAY
xbindkeys
/usr/bin/polybar --config=${XDG_CONFIG_HOME}/polybar/config -r main
dbus-launch --exit-with-session /usr/bin/i3
