#!/usr/bin/env bash

# The point of this is just to nag me about missing software
# that I depend on.  I have made attempts in the past to just
# install things that are missing, however, I work on too varied
# a set of systems to care enough to maintain all of the different
# mechanisms necessary.  So, now I just nag future me and hope
# that I'll do the right thing and install stuff..

function about
{
	hash $1 2>/dev/null || echo "$1 is missing"
}


about zsh
about dunst
about vim
about nvim
about tmux
about sdcv
about curl
about wget
about bat
about cmus
about task
about weechat
about xclip
about notify-send
about i3
about dmenu
about make
about pkg-config
about alacritty
about st
about polybar
about clipmenu
about clipmenud
