#!/usr/bin/env bash

command_help "Install alacritty terminal (if not available via your package manager)" $@
command_require wget tar install rustc cargo

d=$(mktemp -d)
cd $d

uri="https://github.com/alacritty/alacritty/archive/"
file="v0.5.0.tar.gz"
wget ${uri}/${file}
tar xvzf ${file}
#install alacritty $HOME/.local/bin
