#!/usr/bin/env bash

command_help "Install cmus (command-line music player)" $@
command_require git make
set -e

d=$(mktemp -d)
cd $d

git clone git://github.com/cmus/cmus
cd cmus
./configure prefix=$HOME/.local
make && make install
