#!/usr/bin/env bash

command_help "Grab C++ standards into ~/doc/cpp" $@
command_require wget

declare -a uris=(
	"www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4687.pdf"
	"www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf"
	"www.open-std.org/jtc1/sc22/wg21/docs/papers/2012/n3337.pdf"
)

dest=$HOME/docs/cpp
mkdir -p $dest

for uri in ${uris[@]}; do
	name=$(basename $uri)
	wget --quiet $uri -O $dest/$name
done
