#!/usr/bin/env bash

command_help "Install global git aliases" $@
command_require git 

git config --global alias.discard 'restore --'
git config --global alias.tree "log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
git config --global alias.ctags '! $HOME/opt/bin/ctags'
