#!/usr/bin/env bash

command_help "Install playerctl; a command-line MPRIS controller (WIP)" $@
command_require git meson
set -e

d=$(mktemp -d)
cd $d

git clone git://github.com/altdesktop/playerctl
meson -Dgtk-dock=false setup --prefix $HOME/.local build playerctl
meson dist
meson install
