#!/usr/bin/env bash

command_help "Install polybar" $@
command_require git cmake make

d=$(mktemp -d)
cd $d

git clone git://github.com/polybar/polybar
cd polybar
git checkout 3.3.1
git submodule init
git submodule update
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/.local
make -j4
make install
make userconfig
