#!/usr/bin/env bash

news="$HOME/.config/.news"

$HOME/bin/config master fetch
$HOME/bin/config master merge --ff-only origin/master

if [ $? -ne 0 ]; then
	$HOME/bin/config master rebase origin/master

	if [ $? -ne 0 ]; then
		config-news "Sync Dot-Dir requires manual intervention" "
			Failed to FF merge and failed to rebase local
			changes to master when syncing config to origin
			on $(date +%Y%m%d-%H:%M:%S)"
		exit
	fi
fi

$HOME/bin/config master push
