#!/usr/bin/env sh
set -e
trap "rm -rf ${GIT_DIR}/tags.$$" EXIT
echo "regenerating CTAGS (from ${GIT_DIR}/hooks/ctags)"
/usr/bin/env ctags -f ${GIT_DIR}/tags.$$ --tag-relative=yes -R --extra=+q --fields=+afiknsSt --exclude=.git --exclude="*.java" --exclude="*.cs" --exclude="*.js" --exclude="*.py" --exclude="*.sql" --exclude="*.sh"
mv ${GIT_DIR}/tags.$$ ${GIT_DIR}/tags
