setopt null_glob

typeset -U path PATH
typeset -U fpath FPATH
typeset -U manpath MANPATH

func_dirs=($DOTDIR/zsh/functions $LOCALDOTDIR/zsh/functions)
for dir in ${func_dirs[@]}
do
	fpath+=($dir)
	funcs=($dir/*)
	for func in ${funcs[@]}
	do
		autoload ${func:t}
	done
done

recursive_source ${DOTDIR} zshenv
recursive_source ${LOCALDOTDIR} zshenv
