setopt null_glob

recursive_source $DOTDIR zshrc
recursive_source $LOCALDOTDIR zshrc

autoload -U compinit
compinit

recursive_source $DOTDIR zshcomp
recursive_source $LOCALDOTDIR zshcomp

run_outstanding_runonce

[ -n "$STARTUP_COMMANDS" ] && eval "$STARTUP_COMMANDS" && unset STARTUP_COMMANDS
