setopt null_glob

source $DOTDIR/dot/recursive_source.zsh

recursive_source $DOTDIR zshrc
recursive_source $LOCALDOTDIR zshrc

autoload -U compinit
compinit

recursive_source $DOTDIR zshcomp
recursive_source $LOCALDOTDIR zshcomp

source ${DOTDIR}/dot/runonce.zshrc
run_outstanding_runonce

[ -n "$STARTUP_COMMANDS" ] && eval "$STARTUP_COMMANDS" && unset STARTUP_COMMANDS
