#!/usr/bin/env bash

# To install, simply:
# curl -Lks "https://github.com/michael-stevenson/dotfiles/raw/master/docs/README" | bash

uri="https://github.com/michael-stevenson/dotfiles"

mkdir -p $HOME/.dot
git_dir="$HOME/.dot/master"

git clone --bare ${uri} ${git_dir}
git --git-dir=${git_dir} --work-tree=$HOME config status.showUntrackedFiles no
git --git-dir=${git_dir} --work-tree=$HOME checkout

if [ $? != 0 ]; then
	# some pre-existing files collided..
	echo "Some files might have collided, backing-up existing dot files to $HOME/.dot-backup"
	mkdir -p $HOME/.dot-backup
	git --git-dir=${git_dir} --work-tree=$HOME checkout 2>&1 | egrep "\s+\." | awk '{print $1}' | xargs -I{} mv {} $HOME/.dot-backup
	git --git-dir=${git_dir} --work-tree=$HOME checkout
fi

$HOME/.config/.install/install
exit
